services:
#    fake_user.example:
#        class: Fake\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

#fake_user.password_resetting:
#        class: Fake\UserBundle\EventListener\PasswordResettingListener
#        arguments: [@router]
#        tags:
#            - { name: kernel.event_subscriber }
